-- CREATE IF NOT EXISTS TABLE users (
--   id sequence PRIMARY KEY,
--   name VARCHAR(50) NOT NULL,
--   email VARCHAR(50) NOT NULL UNIQUE,
--   password TEXT NOT NULL,
--   created_at TIMESTAMP
--   WITH
--     TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
-- )
CREATE TYPE role AS ENUM ('super_admin', 'admin', 'user')
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role role NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_name ON users (email);

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_created_at ON users (created_at DESC);

CREATE TABLE IF NOT EXISTS users_profile (
  user_id UUID PRIMARY KEY REFERENCES users ON DELETE CASCADE,
  bio TEXT,
  phone TEXT,
  avatar_url TEXT,
  user_name TEXT NOT NULL UNIQUE,
  address JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE status AS ENUM ('active', 'in_active')
CREATE TABLE IF NOT EXIST projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  status status NOT NULL DEFAULT 'active',
  owner_id UUID NOT NULL REFERENCES users ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE task_status AS ENUM ("done", "in_progress", "pending")
CREATE TABLE IF NOT EXIST tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
  project_id UUID NOT NULL REFERENCES projects ON DELETE CASCADE,
  title VARCHAR(100) NOT NULL,
  description TEXT,
  status task_status NOT NULL DEFAULT 'pending',
  priority SMALLINT NOT NULL DEFAULT 0 CHECK (priority BETWEEN 0 AND 5),
  user_id UUID REFERENCES user ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_member (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid (),
  user_id UUID REFERENCES user ON DELETE CASCADE,
  project_id UUId REFERENCES project ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, project_id)
);
